//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFootballProject.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation_To_Rooms
    {
        public int Id { get; set; }
        public int RoomId { get; set; }
        public int RezervId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Rezerv Rezerv { get; set; }
    }
}
